# Feature Engineering

In [145]:
import polars as pl
from pathlib import Path
import tomllib
import os

In [146]:
config_file_path = Path("config.toml")

with config_file_path.open("rb") as config_file:
    config = tomllib.load(config_file)

COMPANIES = config['companies']

In [147]:
company = next(company for company in COMPANIES)

In [148]:
lf = pl.scan_parquet(f'ETL/data/enriched/parquet/{company}_share_prices_enriched.parquet')

In [149]:
lf = lf.with_columns(
    # Log Return
    (pl.col('Adj. Close') / pl.col('Adj. Close').shift(1)).log().alias(f'Log Return')
)

for window in [5, 10, 20]:
    lf = lf.with_columns(
        # Rolling Log Returns
        (pl.col('Adj. Close') / pl.col('Adj. Close').shift(window)).log().alias(f'Log Return {window}d'),

        # Volatility
        pl.col('Log Return').rolling_std(window).log1p().alias(f'Volatility {window}d'),

        # Moving Averages
        pl.col("Adj. Close").rolling_mean(5).alias(f"Moving Average {window}d"),

        # Momentum Pct. Change
        ((pl.col("Adj. Close") / pl.col("Adj. Close").shift(window)) - 1).alias(f"Momentum Pct. {window}d"),

        # Log Volume Ratio
        ((pl.col("Volume") / pl.col("Volume").rolling_mean(window))).log().alias(f"Log Volume Ratio {window}d"),
    )

    lf = lf.with_columns(
        # Log MA Ratio
        (pl.col("Adj. Close") / pl.col(f"Moving Average {window}d")).log().alias(f"Log MA Ratio {window}d")
    )

lf = lf.with_columns(
    # Intraday Returns
    ((pl.col('Close') / pl.col('Open')) - 1).alias('Intraday Pct. Return'),

    # Ranges
    (pl.col('High') - pl.col('Low')).alias('Range'),
    ((pl.col('High') - pl.col('Low')) / pl.col('Close')).alias('Range Pct.'),

    # Close Position
    (((pl.col('Close') - pl.col('Low')) / (pl.col('High') - pl.col('Low'))) - 0.5).alias('Close Position'),

    # Log Volume Change
    (pl.col("Volume") / pl.col("Volume").shift(1)).log().tanh().alias("Log Volume Change"),

    # Log Market Cap
    (pl.col("Adj. Close") * pl.col("Shares Outstanding")).log().alias("Log Market Cap"),

    # Dilution / Issuance
    (pl.col("Shares Outstanding") / pl.col("Shares Outstanding").shift(1) - 1).alias('Delta Pct. Dilution / Issuance'),

    # Volume Return Interaction
    (pl.col("Log Return") * pl.col("Log Volume Ratio 5d")).tanh().alias("Interaction Return Volume 5d"),
    (pl.col("Log Return") * pl.col("Log Volume Ratio 10d")).tanh().alias("Interaction Return Volume 10d"),
    (pl.col("Log Return") * pl.col("Log Volume Ratio 20d")).tanh().alias("Interaction Return Volume 20d"),

    # Volume Volatility Interaction
    (pl.col("Volatility 5d") * pl.col("Log Volume Ratio 5d")).tanh().alias("Interaction Volatility Volume 5d"),
    (pl.col("Volatility 10d") * pl.col("Log Volume Ratio 10d")).tanh().alias("Interaction Volatility Volume 10d"),
    (pl.col("Volatility 20d") * pl.col("Log Volume Ratio 20d")).tanh().alias("Interaction Volatility Volume 20d"),

    # Momentum Volatility Interaction
    (pl.col("Momentum Pct. 5d") * pl.col("Volatility 5d")).tanh().alias("Interaction Momentum Volatility 5d"),
    (pl.col("Momentum Pct. 10d") * pl.col("Volatility 10d")).tanh().alias("Interaction Momentum Volume 10d"),
    (pl.col("Momentum Pct. 20d") * pl.col("Volatility 20d")).tanh().alias("Interaction Momentum Volume 20d"),

    # Target Engineering
    (pl.col("Adj. Close").shift(-1) / pl.col("Adj. Close") - 1).alias("Target Return Metric"),
    ((pl.col("Adj. Close").shift(-1) / pl.col("Adj. Close") - 1) > 0).alias("Target Return Class")
)

In [150]:
with pl.Config(tbl_rows=-1):
    display(lf.head(21).collect())

shape: (21, 44)
┌────────┬────────┬────────┬────────┬───┬────────────────┬────────────────┬───────────────┬────────┐
│ Open   ┆ High   ┆ Low    ┆ Close  ┆ … ┆ Interaction    ┆ Interaction    ┆ Target Return ┆ Target │
│ ---    ┆ ---    ┆ ---    ┆ ---    ┆   ┆ Momentum       ┆ Momentum       ┆ Metric        ┆ Return │
│ f64    ┆ f64    ┆ f64    ┆ f64    ┆   ┆ Volume 10…     ┆ Volume 20…     ┆ ---           ┆ Class  │
│        ┆        ┆        ┆        ┆   ┆ ---            ┆ ---            ┆ f64           ┆ ---    │
│        ┆        ┆        ┆        ┆   ┆ f64            ┆ f64            ┆               ┆ bool   │
╞════════╪════════╪════════╪════════╪═══╪════════════════╪════════════════╪═══════════════╪════════╡
│ 100.86 ┆ 101.79 ┆ 99.88  ┆ 100.58 ┆ … ┆ null           ┆ null           ┆ 0.015609      ┆ true   │
│ 101.05 ┆ 102.2  ┆ 100.56 ┆ 102.15 ┆ … ┆ null           ┆ null           ┆ -0.000098     ┆ false  │
│ 102.22 ┆ 102.65 ┆ 100.88 ┆ 102.14 ┆ … ┆ null           ┆ null           ┆ 0.06168       ┆ true   │
│ 102.0  ┆ 109.0  ┆ 101.9  ┆ 108.44 ┆ … ┆ null           ┆ null           ┆ 0.05284       ┆ true   │
│ 110.02 ┆ 114.6  ┆ 109.31 ┆ 114.17 ┆ … ┆ null           ┆ null           ┆ 0.010598      ┆ true   │
│ 112.88 ┆ 116.67 ┆ 112.25 ┆ 115.38 ┆ … ┆ null           ┆ null           ┆ 0.043595      ┆ true   │
│ 117.3  ┆ 123.05 ┆ 116.75 ┆ 120.41 ┆ … ┆ null           ┆ null           ┆ -0.013786     ┆ false  │
│ 118.62 ┆ 120.0  ┆ 115.8  ┆ 118.75 ┆ … ┆ null           ┆ null           ┆ 0.007832      ┆ true   │
│ 119.5  ┆ 122.25 ┆ 119.3  ┆ 119.68 ┆ … ┆ null           ┆ null           ┆ -0.027323     ┆ false  │
│ 120.83 ┆ 121.42 ┆ 113.98 ┆ 116.41 ┆ … ┆ null           ┆ null           ┆ 0.015119      ┆ true   │
│ 118.45 ┆ 119.7  ┆ 117.55 ┆ 118.17 ┆ … ┆ 0.004829       ┆ null           ┆ 0.015232      ┆ true   │
│ 120.0  ┆ 121.21 ┆ 119.1  ┆ 119.97 ┆ … ┆ 0.004817       ┆ null           ┆ 0.004501      ┆ true   │
│ 120.85 ┆ 121.02 ┆ 119.1  ┆ 120.51 ┆ … ┆ 0.004921       ┆ null           ┆ -0.01419      ┆ false  │
│ 122.16 ┆ 122.24 ┆ 118.15 ┆ 118.8  ┆ … ┆ 0.002323       ┆ null           ┆ -0.026094     ┆ false  │
│ 118.61 ┆ 118.67 ┆ 115.3  ┆ 115.7  ┆ … ┆ 0.00029        ┆ null           ┆ 0.025411      ┆ true   │
│ 116.5  ┆ 119.59 ┆ 115.5  ┆ 118.64 ┆ … ┆ 0.000643       ┆ null           ┆ 0.04265       ┆ true   │
│ 120.99 ┆ 123.75 ┆ 119.8  ┆ 123.7  ┆ … ┆ 0.000617       ┆ null           ┆ -0.07599      ┆ false  │
│ 116.84 ┆ 118.12 ┆ 112.91 ┆ 114.3  ┆ … ┆ -0.001269      ┆ null           ┆ 0.013123      ┆ true   │
│ 112.82 ┆ 116.35 ┆ 112.82 ┆ 115.8  ┆ … ┆ -0.001105      ┆ null           ┆ 0.000777      ┆ true   │
│ 117.0  ┆ 117.55 ┆ 115.36 ┆ 115.89 ┆ … ┆ -0.000148      ┆ null           ┆ 0.01441       ┆ true   │
│ 116.47 ┆ 117.87 ┆ 116.0  ┆ 117.56 ┆ … ┆ -0.00017       ┆ 0.005199       ┆ 0.006975      ┆ true   │
└────────┴────────┴────────┴────────┴───┴────────────────┴────────────────┴───────────────┴────────┘

In [151]:
lf = lf.drop([
    "Open", 
    "High",
    "Low",
    "Close",
    "Adj. Close",
    "Moving Average 5d",
    "Moving Average 10d",
    "Moving Average 20d",
    "Volume",
    "Range",
    "Shares Outstanding"
])

lf = lf.drop_nulls()

In [152]:
with pl.Config(tbl_rows=-1):
    display(lf.head(21).collect())

shape: (21, 33)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Log       ┆ Log       ┆ Volatilit ┆ Momentum  ┆ … ┆ Interacti ┆ Interacti ┆ Target    ┆ Target   │
│ Return    ┆ Return 5d ┆ y 5d      ┆ Pct. 5d   ┆   ┆ on        ┆ on        ┆ Return    ┆ Return   │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ Momentum  ┆ Momentum  ┆ Metric    ┆ Class    │
│ f64       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ Volume    ┆ Volume    ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ 10…       ┆ 20…       ┆ f64       ┆ bool     │
│           ┆           ┆           ┆           ┆   ┆ ---       ┆ ---       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ f64       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0.014307  ┆ -0.009145 ┆ 0.044674  ┆ -0.009103 ┆ … ┆ -0.00017  ┆ 0.005199  ┆ 0.006975  ┆ true     │
│ 0.006951  ┆ -0.043959 ┆ 0.038868  ┆ -0.043007 ┆ … ┆ -0.000433 ┆ 0.004885  ┆ 0.005068  ┆ true     │
│ 0.005056  ┆ 0.040129  ┆ 0.005621  ┆ 0.040945  ┆ … ┆ -0.000415 ┆ 0.005062  ┆ 0.012355  ┆ true     │
│ 0.012279  ┆ 0.03937   ┆ 0.005461  ┆ 0.040155  ┆ … ┆ 0.000453  ┆ 0.003134  ┆ -0.021586 ┆ false    │
│ -0.021822 ┆ 0.016771  ┆ 0.014466  ┆ 0.016913  ┆ … ┆ 0.000599  ┆ 0.000863  ┆ 0.004667  ┆ true     │
│ 0.004656  ┆ 0.00712   ┆ 0.013257  ┆ 0.007145  ┆ … ┆ -0.000063 ┆ 0.000699  ┆ 0.008784  ┆ true     │
│ 0.008745  ┆ 0.008914  ┆ 0.013463  ┆ 0.008954  ┆ … ┆ -0.000967 ┆ -0.000202 ┆ 0.008791  ┆ true     │
│ 0.008753  ┆ 0.012611  ┆ 0.013779  ┆ 0.012691  ┆ … ┆ 0.00056   ┆ 0.000365  ┆ 0.006806  ┆ true     │
│ 0.006782  ┆ 0.007115  ┆ 0.013019  ┆ 0.00714   ┆ … ┆ 0.000476  ┆ 0.000339  ┆ 0.009562  ┆ true     │
│ 0.009517  ┆ 0.038453  ┆ 0.001973  ┆ 0.039202  ┆ … ┆ 0.000569  ┆ 0.001252  ┆ 0.019842  ┆ true     │
│ 0.019647  ┆ 0.053445  ┆ 0.005096  ┆ 0.054899  ┆ … ┆ 0.000665  ┆ 0.001378  ┆ -0.020496 ┆ false    │
│ -0.020709 ┆ 0.02399   ┆ 0.014995  ┆ 0.02428   ┆ … ┆ 0.000453  ┆ 0.000485  ┆ -0.004087 ┆ false    │
│ -0.004095 ┆ 0.011142  ┆ 0.015241  ┆ 0.011204  ┆ … ┆ 0.000329  ┆ 0.000271  ┆ -0.006156 ┆ false    │
│ -0.006175 ┆ -0.001815 ┆ 0.015371  ┆ -0.001814 ┆ … ┆ 0.000072  ┆ 0.00047   ┆ -0.004707 ┆ false    │
│ -0.004718 ┆ -0.01605  ┆ 0.014392  ┆ -0.015922 ┆ … ┆ 0.000255  ┆ 0.000982  ┆ -0.003817 ┆ false    │
│ -0.003824 ┆ -0.039522 ┆ 0.00719   ┆ -0.038751 ┆ … ┆ 0.000159  ┆ 0.000275  ┆ 0.017158  ┆ true     │
│ 0.017013  ┆ -0.0018   ┆ 0.009707  ┆ -0.001798 ┆ … ┆ 0.000274  ┆ -0.000272 ┆ 0.01171   ┆ true     │
│ 0.011642  ┆ 0.013937  ┆ 0.01068   ┆ 0.014035  ┆ … ┆ 0.000315  ┆ 0.000908  ┆ 0.000567  ┆ true     │
│ 0.000566  ┆ 0.020678  ┆ 0.009657  ┆ 0.020894  ┆ … ┆ 0.000235  ┆ 0.000745  ┆ 0.002427  ┆ true     │
│ 0.002424  ┆ 0.02782   ┆ 0.008493  ┆ 0.028211  ┆ … ┆ 0.000143  ┆ 0.000763  ┆ -0.007182 ┆ false    │
│ -0.007208 ┆ 0.024437  ┆ 0.00949   ┆ 0.024738  ┆ … ┆ -0.000156 ┆ 0.000509  ┆ 0.009103  ┆ true     │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [153]:
SILVER_CSV_DIR = os.path.join('ETL', 'data', 'silver', 'csv')
os.makedirs(SILVER_CSV_DIR, exist_ok=True)
filepath = os.path.join(SILVER_CSV_DIR, 'silver_test.csv')
lf.head(50).collect().write_csv(filepath)