# Imports & Setup

In [ ]:
import polars as pl

# Data Cleaning

In [ ]:
companies = pl.read_parquet('data/raw/parquet/companies.parquet')
share_prices = pl.read_parquet('data/raw/parquet/share_prices.parquet')

In [28]:
with pl.Config(tbl_rows=25):
    display(companies.drop_nulls(subset=pl.col('Number Employees')).sort('Number Employees', descending=True).head(25))

shape: (25, 10)
┌──────────┬────────────┬────────────┬────────────┬───┬───────────┬────────┬───────────┬───────────┐
│ SimFinId ┆ Company    ┆ IndustryId ┆ ISIN       ┆ … ┆ Business  ┆ Market ┆ CIK       ┆ Main      │
│ ---      ┆ Name       ┆ ---        ┆ ---        ┆   ┆ Summary   ┆ ---    ┆ ---       ┆ Currency  │
│ i64      ┆ ---        ┆ f64        ┆ str        ┆   ┆ ---       ┆ str    ┆ f64       ┆ ---       │
│          ┆ str        ┆            ┆            ┆   ┆ str       ┆        ┆           ┆ str       │
╞══════════╪════════════╪════════════╪════════════╪═══╪═══════════╪════════╪═══════════╪═══════════╡
│ 62747    ┆ AMAZON COM ┆ 103002.0   ┆ US02313510 ┆ … ┆ Amazon.co ┆ us     ┆ 1.018724e ┆ USD       │
│          ┆ INC        ┆            ┆ 67         ┆   ┆ m Inc is  ┆        ┆ 6         ┆           │
│          ┆            ┆            ┆            ┆   ┆ an online ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ re…       ┆        ┆           ┆           │
│ 106423   ┆ UNITED     ┆ 100010.0   ┆ US91131210 ┆ … ┆ United    ┆ us     ┆ 1.090727e ┆ USD       │
│          ┆ PARCEL     ┆            ┆ 68         ┆   ┆ Parcel    ┆        ┆ 6         ┆           │
│          ┆ SERVICE    ┆            ┆            ┆   ┆ Service   ┆        ┆           ┆           │
│          ┆ INC        ┆            ┆            ┆   ┆ Inc is a… ┆        ┆           ┆           │
│ 61372    ┆ Accenture  ┆ 108002.0   ┆ IE00B4BNMY ┆ … ┆ Accenture ┆ us     ┆ 1.467373e ┆ USD       │
│          ┆ plc        ┆            ┆ 34         ┆   ┆ PLC is a  ┆        ┆ 6         ┆           │
│          ┆            ┆            ┆            ┆   ┆ professio ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ na…       ┆        ┆           ┆           │
│ 233408   ┆ At Home    ┆ 103002.0   ┆ US04650Y10 ┆ … ┆ At Home   ┆ us     ┆ 1.646228e ┆ USD       │
│          ┆ Group Inc. ┆            ┆ 01         ┆   ┆ Group Inc ┆        ┆ 6         ┆           │
│          ┆            ┆            ┆            ┆   ┆ is a home ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ dé…       ┆        ┆           ┆           │
│ 42813    ┆ TESSCO TEC ┆ 101005.0   ┆ US87238610 ┆ … ┆ Tessco    ┆ us     ┆ 927355.0  ┆ USD       │
│          ┆ HNOLOGIES  ┆            ┆ 71         ┆   ┆ Technolog ┆        ┆           ┆           │
│          ┆ INC        ┆            ┆            ┆   ┆ ies Inc   ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ archit…   ┆        ┆           ┆           │
│ 71306    ┆ BERKSHIRE  ┆ 111001.0   ┆ US08467010 ┆ … ┆ Berkshire ┆ us     ┆ 1.067983e ┆ USD       │
│          ┆ HATHAWAY   ┆            ┆ 86         ┆   ┆ Hathaway  ┆        ┆ 6         ┆           │
│          ┆ INC        ┆            ┆            ┆   ┆ Inc.,     ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ throu…    ┆        ┆           ┆           │
│ 18773575 ┆ Fomento    ┆ 102004.0   ┆ US34441910 ┆ … ┆ Fomento   ┆ us     ┆ 1.061736e ┆ USD       │
│          ┆ Económico  ┆            ┆ 64         ┆   ┆ Económico ┆        ┆ 6         ┆           │
│          ┆ Mexicano,  ┆            ┆            ┆   ┆ Mexicano, ┆        ┆           ┆           │
│          ┆ S.…        ┆            ┆            ┆   ┆ S.…       ┆        ┆           ┆           │
│ 86689    ┆ STARBUCKS  ┆ 103003.0   ┆ US85524410 ┆ … ┆ Starbucks ┆ us     ┆ 829224.0  ┆ USD       │
│          ┆ CORP       ┆            ┆ 94         ┆   ┆ Corp is   ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ the       ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ roaster,… ┆        ┆           ┆           │
│ 69543    ┆ INTERNATIO ┆ 101003.0   ┆ US45920010 ┆ … ┆ Internati ┆ us     ┆ 51143.0   ┆ USD       │
│          ┆ NAL        ┆            ┆ 14         ┆   ┆ onal      ┆        ┆           ┆           │
│          ┆ BUSINESS   ┆            ┆            ┆   ┆ Business  ┆        ┆           ┆           │
│          ┆ MACHINE…   ┆            ┆            ┆   ┆ Machine…  ┆        ┆           ┆           │
│ 797860   ┆ TRINET     ┆ 100002.0   ┆ US89628810 ┆ … ┆ Trinet    ┆ us     ┆ 937098.0  ┆ USD       │
│          ┆ GROUP INC  ┆            ┆ 79         ┆   ┆ Group Inc ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ provides  ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ huma…     ┆        ┆           ┆           │
│ 1253405  ┆ JD.com,    ┆ 103002.0   ┆ US47215P10 ┆ … ┆ JD.com,   ┆ us     ┆ 1.549802e ┆ USD       │
│          ┆ Inc.       ┆            ┆ 66         ┆   ┆ Inc.      ┆        ┆ 6         ┆           │
│          ┆            ┆            ┆            ┆   ┆ provides  ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ supply c… ┆        ┆           ┆           │
│ 1253409  ┆ Infosys    ┆ 101003.0   ┆ US45678810 ┆ … ┆ Infosys   ┆ us     ┆ 1.067491e ┆ USD       │
│          ┆ Ltd        ┆            ┆ 85         ┆   ┆ Limited,  ┆        ┆ 6         ┆           │
│          ┆            ┆            ┆            ┆   ┆ together  ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ with…     ┆        ┆           ┆           │
│ 87466    ┆ Walgreens  ┆ 102001.0   ┆ US93142710 ┆ … ┆ Walgreens ┆ us     ┆ 1.618921e ┆ USD       │
│          ┆ Boots      ┆            ┆ 84         ┆   ┆ Boots     ┆        ┆ 6         ┆           │
│          ┆ Alliance,  ┆            ┆            ┆   ┆ Alliance  ┆        ┆           ┆           │
│          ┆ Inc.       ┆            ┆            ┆   ┆ Inc o…    ┆        ┆           ┆           │
│ 58953    ┆ WELLS      ┆ 104002.0   ┆ US94974610 ┆ … ┆ Wells     ┆ us     ┆ 72971.0   ┆ USD       │
│          ┆ FARGO &    ┆            ┆ 15         ┆   ┆ Fargo &   ┆        ┆           ┆           │
│          ┆ COMPANY/MN ┆            ┆            ┆   ┆ Co        ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ operates  ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ as o…     ┆        ┆           ┆           │
│ 692435   ┆ Aramark    ┆ 103003.0   ┆ null       ┆ … ┆ Aramark   ┆ us     ┆ 7032.0    ┆ USD       │
│          ┆ Services,  ┆            ┆            ┆   ┆ is        ┆        ┆           ┆           │
│          ┆ Inc.       ┆            ┆            ┆   ┆ engaged   ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ in the    ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ rest…     ┆        ┆           ┆           │
│ 378161   ┆ HCA        ┆ 106011.0   ┆ US40412C10 ┆ … ┆ HCA Healt ┆ us     ┆ 860730.0  ┆ USD       │
│          ┆ Holdings   ┆            ┆ 18         ┆   ┆ hcare Inc ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ is a      ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ health…   ┆        ┆           ┆           │
│ 361112   ┆ Aramark    ┆ 103003.0   ┆ US03852U10 ┆ … ┆ Aramark   ┆ us     ┆ 1.584509e ┆ USD       │
│          ┆            ┆            ┆ 60         ┆   ┆ is        ┆        ┆ 6         ┆           │
│          ┆            ┆            ┆            ┆   ┆ engaged   ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ in the    ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ rest…     ┆        ┆           ┆           │
│ 217867   ┆ COSTCO     ┆ 102001.0   ┆ US22160K10 ┆ … ┆ Costco    ┆ us     ┆ 909832.0  ┆ USD       │
│          ┆ WHOLESALE  ┆            ┆ 51         ┆   ┆ Wholesale ┆        ┆           ┆           │
│          ┆ CORP /NEW  ┆            ┆            ┆   ┆ Corp and  ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ its …     ┆        ┆           ┆           │
│ 71941    ┆ BANK OF    ┆ 104002.0   ┆ US06050510 ┆ … ┆ Bank of   ┆ us     ┆ 70858.0   ┆ USD       │
│          ┆ AMERICA    ┆            ┆ 46         ┆   ┆ America   ┆        ┆           ┆           │
│          ┆ CORP /DE/  ┆            ┆            ┆   ┆ Corporati ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ on is…    ┆        ┆           ┆           │
│ 18418650 ┆ Banco      ┆ 104002.0   ┆ US05964H10 ┆ … ┆ Banco San ┆ us     ┆ 891478.0  ┆ USD       │
│          ┆ Santander, ┆            ┆ 59         ┆   ┆ tander,   ┆        ┆           ┆           │
│          ┆ S.A.       ┆            ┆            ┆   ┆ S.A.      ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ provides… ┆        ┆           ┆           │
│ 89126    ┆ CITIGROUP  ┆ 104002.0   ┆ US17296742 ┆ … ┆ Citigroup ┆ us     ┆ 831001.0  ┆ USD       │
│          ┆ INC        ┆            ┆ 42         ┆   ┆ Inc is a  ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ financial ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ -s…       ┆        ┆           ┆           │
│ 1239536  ┆ Stellantis ┆ 103005.0   ┆ NL00150001 ┆ … ┆ Stellanti ┆ us     ┆ 1.605484e ┆ USD       │
│          ┆ N.V.       ┆            ┆ Q9         ┆   ┆ s is one  ┆        ┆ 6         ┆           │
│          ┆            ┆            ┆            ┆   ┆ of the    ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ world…    ┆        ┆           ┆           │
│ 243628   ┆ MCDONALDS  ┆ 103003.0   ┆ US58013510 ┆ … ┆ McDonald\ ┆ us     ┆ 63908.0   ┆ USD       │
│          ┆ CORP       ┆            ┆ 17         ┆   ┆ 's Corp   ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ operates  ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ a ch…     ┆        ┆           ┆           │
│ 113871   ┆ STARWOOD   ┆ 103015.0   ┆ null       ┆ … ┆ null      ┆ us     ┆ 316206.0  ┆ USD       │
│          ┆ HOTEL &    ┆            ┆            ┆   ┆           ┆        ┆           ┆           │
│          ┆ RESORTS    ┆            ┆            ┆   ┆           ┆        ┆           ┆           │
│          ┆ WORLD…     ┆            ┆            ┆   ┆           ┆        ┆           ┆           │
│ 249937   ┆ FORD MOTOR ┆ 103005.0   ┆ US34537086 ┆ … ┆ Ford      ┆ us     ┆ 37996.0   ┆ USD       │
│          ┆ CO         ┆            ┆ 00         ┆   ┆ Motor Co  ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ manufactu ┆        ┆           ┆           │
│          ┆            ┆            ┆            ┆   ┆ res var…  ┆        ┆           ┆           │
└──────────┴────────────┴────────────┴────────────┴───┴───────────┴────────┴───────────┴───────────┘

In [24]:
with pl.Config(tbl_rows=25):
    display(share_prices.head(25))

shape: (25, 9)
┌──────────┬────────┬────────┬────────┬───┬────────────┬───────────┬──────────┬────────────────────┐
│ SimFinId ┆ Open   ┆ High   ┆ Low    ┆ … ┆ Adj. Close ┆ Volume    ┆ Dividend ┆ Shares Outstanding │
│ ---      ┆ ---    ┆ ---    ┆ ---    ┆   ┆ ---        ┆ ---       ┆ ---      ┆ ---                │
│ i64      ┆ f64    ┆ f64    ┆ f64    ┆   ┆ f64        ┆ i64       ┆ f64      ┆ f64                │
╞══════════╪════════╪════════╪════════╪═══╪════════════╪═══════════╪══════════╪════════════════════╡
│ 45846    ┆ 118.9  ┆ 120.29 ┆ 117.09 ┆ … ┆ 118.11     ┆ 2650429   ┆ null     ┆ 2.82602317e8       │
│ 367153   ┆ 61.12  ┆ 63.45  ┆ 58.65  ┆ … ┆ 60.38      ┆ 7253326   ┆ null     ┆ 2.63839742e8       │
│ 7962652  ┆ 10.77  ┆ 10.79  ┆ 10.77  ┆ … ┆ 10.79      ┆ 599704    ┆ null     ┆ 9.8498541e7        │
│ 18959140 ┆ 10.34  ┆ 10.34  ┆ 10.34  ┆ … ┆ 10.34      ┆ 7         ┆ null     ┆ null               │
│ 18712193 ┆ 1.01   ┆ 1.03   ┆ 1.01   ┆ … ┆ 1.02       ┆ 4600      ┆ null     ┆ 6.3995782e7        │
│ 11820349 ┆ 11.0   ┆ 11.12  ┆ 9.52   ┆ … ┆ 9.75       ┆ 37879     ┆ null     ┆ 5.826796e6         │
│ 14122297 ┆ 9.49   ┆ 9.49   ┆ 9.49   ┆ … ┆ 9.49       ┆ 0         ┆ null     ┆ 1.81207392e8       │
│ 12444287 ┆ 0.0    ┆ 0.0    ┆ 0.0    ┆ … ┆ 0.0        ┆ 0         ┆ null     ┆ 2.1205e10          │
│ 9076064  ┆ 4.84   ┆ 4.84   ┆ 4.84   ┆ … ┆ 4.84       ┆ 0         ┆ null     ┆ 2.8468e7           │
│ 68568    ┆ 12.02  ┆ 12.21  ┆ 11.53  ┆ … ┆ 11.79      ┆ 125520689 ┆ null     ┆ 6.60304573e8       │
│ 18508049 ┆ 10.65  ┆ 10.67  ┆ 10.65  ┆ … ┆ 10.66      ┆ 7987      ┆ null     ┆ 4.3974e7           │
│ 847094   ┆ 1.33   ┆ 1.34   ┆ 1.21   ┆ … ┆ 1.25       ┆ 18359     ┆ null     ┆ 2.554512e6         │
│ 450021   ┆ 2.69   ┆ 2.69   ┆ 2.6    ┆ … ┆ 2.63       ┆ 3455      ┆ null     ┆ 2.0397228e7        │
│ 441241   ┆ 10.08  ┆ 10.1   ┆ 10.08  ┆ … ┆ 10.09      ┆ 2765717   ┆ null     ┆ 3.0712772e7        │
│ 671827   ┆ 97.49  ┆ 102.28 ┆ 91.35  ┆ … ┆ 101.14     ┆ 10144120  ┆ null     ┆ 7.5198817e7        │
│ 919501   ┆ 95.45  ┆ 95.51  ┆ 91.43  ┆ … ┆ 92.4       ┆ 1357384   ┆ null     ┆ 8.1499853e7        │
│ 184955   ┆ 51.32  ┆ 51.99  ┆ 50.23  ┆ … ┆ 51.26      ┆ 1528045   ┆ null     ┆ 6.01e7             │
│ 111052   ┆ 260.79 ┆ 261.56 ┆ 257.25 ┆ … ┆ 260.29     ┆ 49259600  ┆ null     ┆ 1.4681e10          │
│ 919944   ┆ 19.4   ┆ 19.66  ┆ 19.32  ┆ … ┆ 19.6       ┆ 467820    ┆ 0.34     ┆ 6.1390936e7        │
│ 16787005 ┆ 1.96   ┆ 2.1    ┆ 1.91   ┆ … ┆ 2.04       ┆ 37627     ┆ null     ┆ 76975.0            │
│ 2265764  ┆ 0.56   ┆ 0.57   ┆ 0.51   ┆ … ┆ 0.52       ┆ 11445     ┆ null     ┆ 2.02334004e8       │
│ 762204   ┆ 102.48 ┆ 102.48 ┆ 102.48 ┆ … ┆ 102.48     ┆ 1         ┆ null     ┆ 2.8436e7           │
│ 11794966 ┆ 38.7   ┆ 38.7   ┆ 38.1   ┆ … ┆ 38.54      ┆ 454021    ┆ null     ┆ 9.2284367e7        │
│ 36105    ┆ 83.0   ┆ 83.0   ┆ 83.0   ┆ … ┆ 83.0       ┆ 0         ┆ null     ┆ 2.2871e7           │
│ 61199    ┆ 233.42 ┆ 234.8  ┆ 228.0  ┆ … ┆ 232.35     ┆ 9390203   ┆ null     ┆ 1.7682e9           │
└──────────┴────────┴────────┴────────┴───┴────────────┴───────────┴──────────┴────────────────────┘